```{r include=FALSE}
library(readxl)
library(dplyr)
library(tidyr)

athletes <- read_excel("olympics.xlsx", sheet = "athletes")
country <- read_excel("olympics.xlsx", sheet = "country")
games <- read_excel("olympics.xlsx", sheet = "games")
medals <- read_excel("olympics.xlsx", sheet = "medals")
```

# Report 6
## Exercises
### Part 1
#### Have some athletes competed for different countries over time?

```{r}
summary_athletes <-
country %>%
  group_by(athlete_id) %>%
  mutate(n = n(),
         differnet_countries = n_distinct(NOC)) %>%
  arrange(desc(differnet_countries)) %>%
  ungroup
summary_athletes
```
There are several athletes who have competed for different countries.


### Part 2
#### Who are the ten athletes that took part in most games?
```{r}

max_participations <-
country %>%
  group_by(athlete_id) %>%
  summarise(participations = n()) %>%
  top_n(10) %>%
  arrange(desc(participations))
max_participations
```

### Part 3
#### What athlete(s) kept a Gold medal for the longest time?
```{r}
analysis <-
medals %>%
  filter(Medal == "Gold") %>%
  group_by(Event, athlete_id) %>%
  summarise(gold_medals_per_athlete_event = n()) %>%
  arrange(desc(gold_medals_per_athlete_event)) %>%
  ungroup()
analysis
```

### Part 4
#### What country(ies) kept a Gold medal for the longest time?

```{r}
analysis <-
medals %>%
  filter(Medal == "Gold") %>%
  group_by(Event, Team) %>%
  summarise(gold_medals_per_country_event = n()) %>%
  arrange(desc(gold_medals_per_country_event)) 
analysis
```
