```{r include=FALSE}
library(dplyr)
library(DBI)
library(purrr)
library(tidyverse)

politicians_db <- dbConnect(RSQLite::SQLite(), "zh_politicians.db")

addresses_tbl <- tbl(politicians_db, "Addresses")
affilations_tbl <- tbl(politicians_db, "Affiliations")
mandates_tbl <- tbl(politicians_db, "Mandates")
persons_tbl <- tbl(politicians_db, "Persons")

library(lubridate)
library(janitor)

mandates <-
mandates_tbl%>%
  collect



```

# Report 3
## Exercises
### Part 1
#### How many survey participants were there?
```{r}

jim <-
mandates %>%
  filter(MANDATE_START_DAY > 0) %>%
  mutate(StartDate = make_date(MANDATE_START_YEAR, MANDATE_START_MONTH, MANDATE_START_DAY),
         MANDATE_END_YEAR = case_when(
         MANDATE_END_YEAR==0 ~ as.integer(format(Sys.Date(),'%Y')),
         TRUE ~ MANDATE_END_YEAR),
         MANDATE_END_MONTH = case_when(
         MANDATE_END_MONTH==0 ~ as.integer(format(Sys.Date(),'%m')),
         TRUE ~ MANDATE_END_MONTH),
         MANDATE_END_DAY = case_when(
         MANDATE_END_DAY==0 ~ as.integer(format(Sys.Date(),'%d')),
         TRUE ~ MANDATE_END_DAY),
         active_years = map2(MANDATE_START_YEAR, MANDATE_END_YEAR, seq))
jim

```


{r include=FALSE}
dbDisconnect(politicians_db)
```
